{"name":"DF agent - load stg_dim_agent","ppdf:dataflowId":"a5b2663f-59df-4a84-b2f9-e485bfe2b082","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"351c8a57-6d48-47a4-941c-9da16fccacd2"},"ppdf:fastCopy":true,"version":"1.0","culture":"es-ES","modifiedTime":"2024-12-28T23:43:03.0836111+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"agents_info csv":{"queryId":"4b1ed7d0-c930-4666-b7d8-7fc002ed35b5","queryName":"agents_info csv","loadEnabled":true},"agents_info csv_DataDestination":{"queryId":"19fe21c0-821b-4799-82cd-710562df271e","queryName":"agents_info csv_DataDestination"},"agents_info csv_WriteToDataDestination":{"queryId":"6b8f00e4-17f5-4ee0-b0b8-03cbe00e32c7","queryName":"agents_info csv_WriteToDataDestination"},"agents_info csv_TransformForWriteToDataDestination":{"queryId":"73f6dc26-43ab-4172-abb0-573358dd5929","queryName":"agents_info csv_TransformForWriteToDataDestination"},"FastCopyStaging":{"queryId":"6e351fed-4b9c-4c07-af88-41e5e0cd2d3a","queryName":"FastCopyStaging"}},"document":"section Section1;\r\n[Staging = \"FastCopyStaging\"]\r\nshared #\"agents_info csv\" = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[lakehouseId = \"8deda1cd-e23e-430f-b755-075b107caebd\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"agents_info.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 2\", [Delimiter = \";\", Columns = 6, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"agent_name\", type text}, {\"agent_role\", type text}, {\"agent_team\", type text}, {\"agent_department\", type text}, {\"agent_id\", type text}, {\"hire_date\", Int64.Type}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Changed column type\", \"Team \", \"\", Replacer.ReplaceText, {\"agent_team\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Replaced value\", {\"agent_id\", \"agent_name\", \"agent_role\", \"agent_team\", \"agent_department\", \"hire_date\"}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Reordered columns\", {{\"hire_date\", type text}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type 1\", \"hire_year\", each if Text.Contains(Text.From([hire_date]), \"202\") then Text.Middle(Text.From([hire_date]), Text.PositionOf(Text.From([hire_date]), \"202\"), 4) \r\n   else if Text.Contains(Text.From([hire_date]), \"201\") then Text.Middle(Text.From([hire_date]), Text.PositionOf(Text.From([hire_date]), \"201\"), 4) \r\n   else null), {{\"hire_year\", type text}}),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Added custom\", \"hire_month\", each if Text.Middle(Text.From([hire_date]), 0, 4) = [hire_year] then Text.Middle(Text.From([hire_date]), 4, 2)\r\n   else if Text.Middle(Text.From([hire_date]), 4, 4) = [hire_year] then Text.Middle(Text.From([hire_date]), 2, 2)\r\n   else null),\r\n  #\"Added custom 2\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added custom 1\", \"hire_day\", each if Text.Middle(Text.From([hire_date]), 0, 4) = [hire_year] then Text.Middle(Text.From([hire_date]), 6, 2)\r\n   else if Text.Middle(Text.From([hire_date]), 4, 4) = [hire_year] then Text.Middle(Text.From([hire_date]), 0, 2)\r\n   else null), {{\"hire_day\", type text}}),\r\n  #\"Inserted merged column\" = Table.AddColumn(#\"Added custom 2\", \"new_hire_date\", each Text.Combine({[hire_day], Text.From([hire_month]), [hire_year]}, \"/\"), type text),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Inserted merged column\", {{\"new_hire_date\", type date}}),\r\n  #\"Inserted age\" = Table.AddColumn(#\"Changed column type 2\", \"Age\", each DateTimeZone.LocalNow() - DateTimeZone.From([new_hire_date]), type nullable duration),\r\n  #\"Calculated total years\" = Table.TransformColumns(#\"Inserted age\", {{\"Age\", each Duration.TotalDays(_) / 365, type nullable number}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Calculated total years\", {{\"Age\", \"agent_experience_years\"}}),\r\n  #\"Rounded down\" = Table.TransformColumns(#\"Renamed columns\", {{\"agent_experience_years\", each Number.RoundDown(_), type nullable Int64.Type}}),\r\n  #\"Added custom 3\" = Table.AddColumn(#\"Rounded down\", \"agent_experience_LVL\", each let\r\n    ExperienceCategory = \r\n        if [agent_experience_years] < 1 then \"Less than 1 year\"\r\n        else if [agent_experience_years] >= 1 and [agent_experience_years] < 2 then \"1-2 years\"\r\n        else if [agent_experience_years] >= 2 and [agent_experience_years] < 3 then \"2-3 years\"\r\n        else if [agent_experience_years] >= 3 and [agent_experience_years] < 4 then \"3-4 years\"\r\n        else if [agent_experience_years] >= 4 and [agent_experience_years] < 5 then \"4-5 years\"\r\nelse \"5 years or more\"\r\nin\r\n    ExperienceCategory),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Added custom 3\", {{\"agent_experience_LVL\", type text}})\r\nin\r\n  #\"Changed column type 3\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared #\"agents_info csv_DataDestination\" = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"stg_dim_agent\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"FastCopyStaging\"]\r\nshared #\"agents_info csv_WriteToDataDestination\" = let\r\n  #\"agents_info csv_WriteToDataDestination\" = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = #\"agents_info csv_DataDestination\"], (txn) => {TableAction.InsertRows(txn[Target], #\"agents_info csv_TransformForWriteToDataDestination\"), Action.DoNothing}))\r\nin\r\n  #\"agents_info csv_WriteToDataDestination\";\r\nshared #\"agents_info csv_TransformForWriteToDataDestination\" = let\r\n    ColumnMappings = {[SourceColumnName = \"agent_id\", DestinationColumnName = \"bk_agent\"], [SourceColumnName = \"agent_name\", DestinationColumnName = \"agent_name\"], [SourceColumnName = \"agent_role\", DestinationColumnName = \"agent_role\"], [SourceColumnName = \"agent_team\", DestinationColumnName = \"agent_team\"], [SourceColumnName = \"agent_department\", DestinationColumnName = \"agent_department\"], [SourceColumnName = \"agent_experience_years\", DestinationColumnName = \"agent_experience_years\"], [SourceColumnName = \"agent_experience_LVL\", DestinationColumnName = \"agent_experience_LVL\"]},\r\n    SourceColumns = Table.SelectColumns(#\"agents_info csv\", List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\nshared FastCopyStaging = let\r\n  FastCopyStaging = Pipeline.FastCopyModelStorage(DefaultStaging, [Required = false])\r\nin\r\n  FastCopyStaging;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null},{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"agents_info csv","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"agents_info%20csv.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"agent_id","dataType":"string"},{"name":"agent_name","dataType":"string"},{"name":"agent_role","dataType":"string"},{"name":"agent_team","dataType":"string"},{"name":"agent_department","dataType":"string"},{"name":"hire_date","dataType":"string"},{"name":"hire_year","dataType":"string"},{"name":"hire_month","dataType":"string"},{"name":"hire_day","dataType":"string"},{"name":"new_hire_date","dataType":"date"},{"name":"agent_experience_years","dataType":"int64"},{"name":"agent_experience_LVL","dataType":"string"}]}]}