{"name":"DF customer - load DW dim_customer","ppdf:dataflowId":"372fe1d2-88f9-4ea6-bb90-88591a006598","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"c821fbf7-1434-4ae1-861c-f97b0b282ebd"},"ppdf:fastCopy":true,"version":"1.0","culture":"en-US","modifiedTime":"2025-01-08T22:52:56.3989604+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"stg_dim_customer":{"queryId":"e921ecfe-2388-4bb8-9a46-98e03b91e67e","queryName":"stg_dim_customer","loadEnabled":true},"LastSK":{"queryId":"3a6c9f6e-8454-4d6d-b0f2-fd58975aa29f","queryName":"LastSK"},"stg_dim_customer_DataDestination":{"queryId":"849ba11b-e779-4d26-b026-967b921409c2","queryName":"stg_dim_customer_DataDestination"},"stg_dim_customer_WriteToDataDestination":{"queryId":"90a12839-39b8-49bd-b73d-c9b271c4c8a1","queryName":"stg_dim_customer_WriteToDataDestination"},"stg_dim_customer_TransformForWriteToDataDestination":{"queryId":"153de938-dec0-4ece-ab12-26eec72d9d05","queryName":"stg_dim_customer_TransformForWriteToDataDestination"},"FastCopyStaging":{"queryId":"05b4ae33-0a78-4d7e-b705-0ca1a5265088","queryName":"FastCopyStaging"}},"document":"section Section1;\r\n[Staging = \"FastCopyStaging\"]\r\nshared stg_dim_customer = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"stg_dim_customer\"]}[Data],\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Navigation 1\", \"update_day_time\", each DateTime.LocalNow()), {{\"update_day_time\", type datetime}}),\r\n  #\"Added index\" = Table.AddIndexColumn(#\"Added custom\", \"Index\", LastSK, 1, Int64.Type),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Added index\", {{\"Index\", \"sk_customer\"}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Renamed columns\", {\"sk_customer\", \"bk_customer\", \"customer_first_name\", \"customer_surname\", \"customer_age\", \"customer_gender\", \"customer_city\", \"customer_region\", \"customer_state\", \"customer_city_longitude\", \"customer_city_latitude\", \"update_day_time\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Reordered columns\", {{\"update_day_time\", \"load_date_time\"}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Renamed columns 1\", {\"customer_first_name\", \"customer_surname\", \"customer_age\", \"customer_gender\", \"customer_city\", \"customer_region\", \"customer_state\", \"customer_city_longitude\", \"customer_city_latitude\", \"load_date_time\"})\r\nin\r\n  #\"Removed duplicates\";\r\nshared LastSK = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"dim_customer\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"sk_customer\"}),\r\n  #\"Drill down\" = #\"Choose columns\"[sk_customer],\r\n  #\"Calculated maximum\" = if List.Max(#\"Drill down\") = null then 1 else List.Max(#\"Drill down\") + 1\r\nin\r\n  #\"Calculated maximum\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared stg_dim_customer_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"dim_customer\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"FastCopyStaging\"]\r\nshared stg_dim_customer_WriteToDataDestination = let\r\n  stg_dim_customer_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = stg_dim_customer_DataDestination], (txn) => {TableAction.InsertRows(txn[Target], stg_dim_customer_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  stg_dim_customer_WriteToDataDestination;\r\nshared stg_dim_customer_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(stg_dim_customer, {\"sk_customer\", \"bk_customer\", \"customer_first_name\", \"customer_surname\", \"customer_age\", \"customer_gender\", \"customer_city\", \"customer_region\", \"customer_state\", \"customer_city_longitude\", \"customer_city_latitude\", \"load_date_time\"})\r\nin\r\n    SourceTable;\r\nshared FastCopyStaging = let\r\n  FastCopyStaging = Pipeline.FastCopyModelStorage(DefaultStaging, [Required = false])\r\nin\r\n  FastCopyStaging;\r\n","connectionOverrides":[{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"stg_dim_customer","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"stg_dim_customer.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"customer_first_name\",\"customer_surname\",\"customer_age\",\"customer_gender\",\"customer_city\",\"customer_region\",\"customer_state\",\"customer_city_longitude\",\"customer_city_latitude\",\"load_date_time\"]}]"}],"attributes":[{"name":"sk_customer","dataType":"int64"},{"name":"bk_customer","dataType":"string"},{"name":"customer_first_name","dataType":"string"},{"name":"customer_surname","dataType":"string"},{"name":"customer_age","dataType":"int64"},{"name":"customer_gender","dataType":"string"},{"name":"customer_city","dataType":"string"},{"name":"customer_region","dataType":"string"},{"name":"customer_state","dataType":"string"},{"name":"customer_city_longitude","dataType":"decimal"},{"name":"customer_city_latitude","dataType":"decimal"},{"name":"load_date_time","dataType":"dateTime"}]}]}