{"name":"DF customer - load stg_dim_customer","ppdf:dataflowId":"8076b23d-f4ac-4fdc-80a7-e8328c639aca","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"351c8a57-6d48-47a4-941c-9da16fccacd2"},"ppdf:fastCopy":true,"version":"1.0","culture":"en-US","modifiedTime":"2025-01-08T22:20:24.763772+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"customer_info csv":{"queryId":"49881745-2f32-4055-8204-e757e3980644","queryName":"customer_info csv","loadEnabled":true},"AggregatedHash":{"queryId":"cf0eda75-a492-4f96-a5db-4f0ebbfb1cd3","queryName":"AggregatedHash","loadEnabled":true},"uscoordinates_info csv":{"queryId":"ba1feb74-dfa7-45c7-8d60-302612b1393d","queryName":"uscoordinates_info csv","loadEnabled":true},"customer_info csv_DataDestination":{"queryId":"914e5b46-0e8a-44a5-b784-f064462f4b10","queryName":"customer_info csv_DataDestination"},"customer_info csv_WriteToDataDestination":{"queryId":"9bdf4866-ab37-4407-8f82-0fdc93e8de9e","queryName":"customer_info csv_WriteToDataDestination"},"customer_info csv_TransformForWriteToDataDestination":{"queryId":"d05ebeef-765e-4342-b76c-d53ad77c07b9","queryName":"customer_info csv_TransformForWriteToDataDestination"},"FastCopyStaging":{"queryId":"c1da73fb-68d8-4905-837a-a0a7a5fed278","queryName":"FastCopyStaging"}},"document":"section Section1;\r\n[Staging = \"FastCopyStaging\"]\r\nshared #\"customer_info csv\" = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[lakehouseId = \"8deda1cd-e23e-430f-b755-075b107caebd\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"customer_info.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 2\", [Delimiter = \";\", Columns = 7, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"customer_id\", type text}, {\"age\", Int64.Type}, {\"gender\", type text}, {\"city\", type text}, {\"first_name\", type text}, {\"surname\", type text}, {\"state\", type text}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Changed column type\", {\"city\"}, #\"uscoordinates_info csv\", {\"city_name\"}, \"uscoordinates_info csv\", JoinKind.LeftOuter),\r\n  #\"Expanded uscoordinates_info csv\" = Table.ExpandTableColumn(#\"Merged queries\", \"uscoordinates_info csv\", {\"lat_info\", \"lng_info\", \"region_name\"}, {\"lat_info\", \"lng_info\", \"region_name\"}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Expanded uscoordinates_info csv\", {{\"customer_id\", Order.Ascending}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Sorted rows\", \"Hash\", each Binary.ToText( Text.ToBinary( Text.Combine(List.Transform({[customer_id], [first_name], [surname], [age], [gender], [city], [state]}, each if _ = null then \"\" else Text.From(_)), \"|\")), BinaryEncoding.Hex)), {{\"Hash\", type text}}),\r\n  #\"Merged queries 1\" = Table.NestedJoin(#\"Added custom\", {\"Hash\"}, AggregatedHash, {\"Hash\"}, \"AggregatedHash\", JoinKind.LeftOuter),\r\n  #\"Expanded AggregatedHash\" = Table.ExpandTableColumn(#\"Merged queries 1\", \"AggregatedHash\", {\"Count\"}, {\"Count\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded AggregatedHash\", {{\"Count\", \"is_in_dw\"}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Renamed columns\", null, 0, Replacer.ReplaceValue, {\"is_in_dw\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Replaced value\", each [is_in_dw] = 0),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Filtered rows\", {\"customer_id\"})\r\nin\r\n  #\"Removed duplicates\";\r\nshared AggregatedHash = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"dim_customer\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"bk_customer\", \"customer_first_name\", \"customer_surname\", \"customer_age\", \"customer_gender\", \"customer_city\", \"customer_state\"}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Choose columns\", \"Hash\", each Binary.ToText( Text.ToBinary( Text.Combine(List.Transform({[bk_customer], [customer_first_name],[customer_surname], [customer_age], [customer_gender], [customer_city], [customer_state]}, each if _ = null then \"\" else Text.From(_)), \"|\")), BinaryEncoding.Hex)), {{\"Hash\", type text}}),\r\n  #\"Grouped rows\" = Table.Group(#\"Added custom\", {\"Hash\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}})\r\nin\r\n  #\"Grouped rows\";\r\nshared #\"uscoordinates_info csv\" = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[lakehouseId = \"8deda1cd-e23e-430f-b755-075b107caebd\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"uscoordinates_info.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 2\", [Delimiter = \";\", Columns = 6, QuoteStyle = QuoteStyle.None]),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Imported CSV\", \",\", \".\", Replacer.ReplaceText, {\"Column1\", \"Column2\"}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Replaced value\", [PromoteAllScalars = true]),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"lng_info\", type number}, {\"lat_info\", type number}})\r\nin\r\n  #\"Changed column type 1\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared #\"customer_info csv_DataDestination\" = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"stg_dim_customer\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"FastCopyStaging\"]\r\nshared #\"customer_info csv_WriteToDataDestination\" = let\r\n  #\"customer_info csv_WriteToDataDestination\" = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = #\"customer_info csv_DataDestination\"], (txn) => {TableAction.InsertRows(txn[Target], #\"customer_info csv_TransformForWriteToDataDestination\"), Action.DoNothing}))\r\nin\r\n  #\"customer_info csv_WriteToDataDestination\";\r\nshared #\"customer_info csv_TransformForWriteToDataDestination\" = let\r\n    ColumnMappings = {[SourceColumnName = \"customer_id\", DestinationColumnName = \"bk_customer\"], [SourceColumnName = \"first_name\", DestinationColumnName = \"customer_first_name\"], [SourceColumnName = \"surname\", DestinationColumnName = \"customer_surname\"], [SourceColumnName = \"age\", DestinationColumnName = \"customer_age\"], [SourceColumnName = \"gender\", DestinationColumnName = \"customer_gender\"], [SourceColumnName = \"city\", DestinationColumnName = \"customer_city\"], [SourceColumnName = \"region_name\", DestinationColumnName = \"customer_region\"], [SourceColumnName = \"state\", DestinationColumnName = \"customer_state\"], [SourceColumnName = \"lng_info\", DestinationColumnName = \"customer_city_longitude\"], [SourceColumnName = \"lat_info\", DestinationColumnName = \"customer_city_latitude\"]},\r\n    SourceColumns = Table.SelectColumns(#\"customer_info csv\", List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\nshared FastCopyStaging = let\r\n  FastCopyStaging = Pipeline.FastCopyModelStorage(DefaultStaging, [Required = false])\r\nin\r\n  FastCopyStaging;\r\n","connectionOverrides":[{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"customer_info csv","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"customer_info%20csv.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"customer_id\"]}]"}],"attributes":[{"name":"customer_id","dataType":"string"},{"name":"age","dataType":"int64"},{"name":"gender","dataType":"string"},{"name":"city","dataType":"string"},{"name":"first_name","dataType":"string"},{"name":"surname","dataType":"string"},{"name":"state","dataType":"string"},{"name":"lat_info","dataType":"double"},{"name":"lng_info","dataType":"double"},{"name":"region_name","dataType":"string"},{"name":"Hash","dataType":"string"},{"name":"is_in_dw","dataType":"double"}]},{"$type":"LocalEntity","name":"AggregatedHash","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"AggregatedHash.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"Hash\"]}]"}],"attributes":[{"name":"Hash","dataType":"string"},{"name":"Count","dataType":"int64"}]},{"$type":"LocalEntity","name":"uscoordinates_info csv","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"uscoordinates_info%20csv.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"lat_info","dataType":"double"},{"name":"lng_info","dataType":"double"},{"name":"city_name","dataType":"string"},{"name":"state_id","dataType":"string"},{"name":"state_name","dataType":"string"},{"name":"region_name","dataType":"string"}]}],"relationships":[{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"AggregatedHash","attributeName":"Hash"},"toAttribute":{"entityName":"customer_info csv","attributeName":"Hash"}}]}