{"name":"DF date - load stg_dim_date","ppdf:dataflowId":"38484823-d4f3-4928-a9d5-ad066f6f46d1","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"351c8a57-6d48-47a4-941c-9da16fccacd2"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2025-04-11T18:11:34.8090639+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Query":{"queryId":"bebf43de-f1cc-41ea-8b7b-488de6e6ae1e","queryName":"Query","loadEnabled":true},"DefaultStaging":{"queryId":"5a9df56b-4309-4be5-b2c3-534808f4de7c","queryName":"DefaultStaging"},"Query_DataDestination":{"queryId":"ab2e8c33-3267-47bd-8160-139da3c01a49","queryName":"Query_DataDestination"},"Query_WriteToDataDestination":{"queryId":"11969673-03d6-407e-95b0-c45b61f7935c","queryName":"Query_WriteToDataDestination"},"Query_TransformForWriteToDataDestination":{"queryId":"8aa137ce-8f09-4500-8bc5-6c7eadf63414","queryName":"Query_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared Query = let\r\n  Query = List.Dates(#date(2017,01,01), Number.From(#date(2024,01,01)) - Number.From(#date(2017,01,01)), #duration(1, 0, 0, 0)),\r\n  #\"Converted to table\" = Table.FromList(Query, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Converted to table\", {{\"Column1\", type date}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Column1\", \"proper_date\"}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Renamed columns\", \"day\", each Date.Day([proper_date])),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Added custom\", \"Day of week\", each Date.DayOfWeek([proper_date])),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom 1\", {{\"day\", Int64.Type}, {\"Day of week\", Int64.Type}}),\r\n  #\"Added custom 2\" = Table.AddColumn(#\"Changed column type 1\", \"Day name\", each Date.DayOfWeekName([proper_date])),\r\n  #\"Added custom 3\" = Table.AddColumn(#\"Added custom 2\", \"Quarter\", each Date.QuarterOfYear([proper_date])),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Added custom 3\", {{\"Quarter\", type number}, {\"Day name\", type text}}),\r\n  #\"Added custom 4\" = Table.AddColumn(#\"Changed column type 2\", \"Month name\", each Date.MonthName([proper_date])),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Added custom 4\", {{\"Month name\", type text}}),\r\n  #\"Added custom 5\" = Table.AddColumn(#\"Changed column type 3\", \"Year\", each Date.Year([proper_date])),\r\n  #\"Inserted month\" = Table.AddColumn(#\"Added custom 5\", \"Month\", each Date.Month([proper_date]), type nullable number),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Inserted month\", \"Semester number\", each if [Month] <= 6 then 1 else 2),\r\n  #\"Changed column type 9\" = Table.TransformColumnTypes(#\"Inserted conditional column\", {{\"Semester number\", Int64.Type}}),\r\n  #\"Inserted conditional column 1\" = Table.AddColumn(#\"Changed column type 9\", \"Semester name\", each if [Semester number] = 1 then \"S1\" else \"S2\"),\r\n  #\"Inserted conditional column 2\" = Table.AddColumn(#\"Inserted conditional column 1\", \"Quarter name\", each if [Quarter] = 1 then \"Q1\" else if [Quarter] = 2 then \"Q2\" else if [Quarter] = 3 then \"Q3\" else \"Q4\"),\r\n  #\"Changed column type 10\" = Table.TransformColumnTypes(#\"Inserted conditional column 2\", {{\"Quarter name\", type text}, {\"Semester name\", type text}}),\r\n  #\"Added custom 6\" = Table.AddColumn(#\"Changed column type 10\", \"sk_date\", each Text.Combine({Date.ToText([proper_date], \"yyyy\"), Date.ToText([proper_date], \"%d\"), Date.ToText([proper_date], \"%M\")})),\r\n  #\"Changed column type 4\" = Table.TransformColumnTypes(#\"Added custom 6\", {{\"sk_date\", Int64.Type}, {\"Year\", Int64.Type}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type 4\", {\"sk_date\", \"proper_date\", \"day\", \"Day of week\", \"Day name\", \"Quarter\", \"Month name\", \"Year\"}),\r\n  #\"Added custom 7\" = Table.AddColumn(#\"Reordered columns\", \"Custom\", each Date.ToText([proper_date], \"dddd, MMMM dd, yyyy\")),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Added custom 7\", {{\"Custom\", \"Full_date\"}, {\"Month name\", \"Month_name\"}, {\"Day name\", \"weekday_name\"}}),\r\n  #\"Added custom 8\" = Table.AddColumn(#\"Renamed columns 1\", \"Custom\", each Text.Middle(Date.DayOfWeekName([proper_date]), 0, 3)),\r\n  #\"Renamed columns 2\" = Table.RenameColumns(#\"Added custom 8\", {{\"Custom\", \"weekday_name_short\"}}),\r\n  #\"Changed column type 5\" = Table.TransformColumnTypes(#\"Renamed columns 2\", {{\"weekday_name_short\", type text}, {\"Full_date\", type text}}),\r\n  #\"Added custom 9\" = Table.AddColumn(#\"Changed column type 5\", \"month_name_short\", each Date.ToText([proper_date], \"MMM\")),\r\n  #\"Renamed columns 3\" = Table.RenameColumns(#\"Added custom 9\", {{\"Quarter\", \"Quarter_number\"}}),\r\n  #\"Added custom 10\" = Table.AddColumn(#\"Renamed columns 3\", \"Season_number\", each if Date.Month([proper_date]) = 12 or Date.Month([proper_date]) = 1 or Date.Month([proper_date]) = 2 then 1\r\nelse if Date.Month([proper_date]) = 3 or Date.Month([proper_date]) = 4 or Date.Month([proper_date]) = 5 then 2\r\nelse if Date.Month([proper_date]) = 6 or Date.Month([proper_date]) = 7 or Date.Month([proper_date]) = 8 then 3\r\nelse 4),\r\n  #\"Added custom 11\" = Table.AddColumn(#\"Added custom 10\", \"Season_name\", each if Date.Month([proper_date]) = 12 or Date.Month([proper_date]) = 1 or Date.Month([proper_date]) = 2 then \"Winter\"\r\nelse if Date.Month([proper_date]) = 3 or Date.Month([proper_date]) = 4 or Date.Month([proper_date]) = 5 then \"Spring\"\r\nelse if Date.Month([proper_date]) = 6 or Date.Month([proper_date]) = 7 or Date.Month([proper_date]) = 8 then \"Summer\"\r\nelse \"Fall\"),\r\n  #\"Added custom 12\" = Table.AddColumn(#\"Added custom 11\", \"season_name_short\", each if Date.Month([proper_date]) = 12 or Date.Month([proper_date]) = 1 or Date.Month([proper_date]) = 2 then \"Win\"\r\nelse if Date.Month([proper_date]) = 3 or Date.Month([proper_date]) = 4 or Date.Month([proper_date]) = 5 then \"Spr\"\r\nelse if Date.Month([proper_date]) = 6 or Date.Month([proper_date]) = 7 or Date.Month([proper_date]) = 8 then \"Sum\"\r\nelse \"Fal\"),\r\n  #\"Added custom 13\" = Table.AddColumn(#\"Added custom 12\", \"Is_weekend\", each if Date.DayOfWeek([proper_date], Day.Monday) >= 5 then \"Yes\" else \"No\"),\r\n  #\"Changed column type 6\" = Table.TransformColumnTypes(#\"Added custom 13\", {{\"season_name_short\", type text}, {\"Season_name\", type text}, {\"Season_number\", Int64.Type}, {\"Is_weekend\", type text}, {\"month_name_short\", type text}, {\"Quarter_number\", Int64.Type}}),\r\n  #\"Added custom 14\" = Table.AddColumn(#\"Changed column type 6\", \"Promotion_seasonality\", each if (Date.Month([proper_date]) = 11 and Date.Day([proper_date]) >= 24 and Date.DayOfWeek([proper_date]) = 5) then \"Black Friday\"\r\nelse if (Date.Month([proper_date]) = 11 and Date.DayOfWeek([proper_date]) = 1 and Date.Day([proper_date]) > 24) then \"Cyber Monday\"\r\nelse if (Date.Month([proper_date]) = 8 or (Date.Month([proper_date]) = 9 and Date.Day([proper_date]) <= 15)) then \"Back-to-School\"\r\nelse if (Date.Month([proper_date]) = 12 or (Date.Month([proper_date]) = 11 and Date.Day([proper_date]) >= 25)) then \"Holiday Shopping\"\r\nelse if (Date.Month([proper_date]) = 6 or Date.Month([proper_date]) = 7) then \"Summer Sale\"\r\nelse \"No Promotion\"),\r\n  #\"Changed column type 7\" = Table.TransformColumnTypes(#\"Added custom 14\", {{\"Promotion_seasonality\", type text}}),\r\n  #\"Renamed columns 4\" = Table.RenameColumns(#\"Changed column type 7\", {{\"Full_date\", \"full_date\"}, {\"Season_number\", \"season_number\"}, {\"Season_name\", \"season_name\"}, {\"Promotion_seasonality\", \"promotion_seasonality\"}, {\"Year\", \"year\"}, {\"Month_name\", \"month_name\"}, {\"Quarter_number\", \"quarter_number\"}, {\"Day of week\", \"weekday_number\"}, {\"day\", \"monthday_number\"}}),\r\n  #\"Added custom 15\" = Table.AddColumn(#\"Renamed columns 4\", \"quarter_name\", each \"Q\" & Text.From(Date.QuarterOfYear([proper_date]))),\r\n  #\"Changed column type 8\" = Table.TransformColumnTypes(#\"Added custom 15\", {{\"quarter_name\", type text}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type 8\", {\"Quarter name\"}),\r\n  #\"Changed column type 11\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"proper_date\", type datetime}, {\"Month\", Int64.Type}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Changed column type 11\", {\"sk_date\"})\r\nin\r\n  #\"Removed duplicates\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared Query_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"stg_dim_date\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"DefaultStaging\"]\r\nshared Query_WriteToDataDestination = let\r\n  Query_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = Query_DataDestination], (txn) => {TableAction.InsertRows(txn[Target], Query_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  Query_WriteToDataDestination;\r\nshared Query_TransformForWriteToDataDestination = let\r\n    ColumnMappings = {[SourceColumnName = \"sk_date\", DestinationColumnName = \"sk_date\"], [SourceColumnName = \"proper_date\", DestinationColumnName = \"proper_date\"], [SourceColumnName = \"year\", DestinationColumnName = \"year\"], [SourceColumnName = \"Semester number\", DestinationColumnName = \"semester_number\"], [SourceColumnName = \"Semester name\", DestinationColumnName = \"semester_name\"], [SourceColumnName = \"quarter_number\", DestinationColumnName = \"quarter_number\"], [SourceColumnName = \"quarter_name\", DestinationColumnName = \"quarter_name\"], [SourceColumnName = \"Month\", DestinationColumnName = \"month_number\"], [SourceColumnName = \"month_name\", DestinationColumnName = \"month_name\"], [SourceColumnName = \"month_name_short\", DestinationColumnName = \"month_name_short\"], [SourceColumnName = \"monthday_number\", DestinationColumnName = \"monthday_number\"], [SourceColumnName = \"weekday_number\", DestinationColumnName = \"weekday_number\"], [SourceColumnName = \"weekday_name\", DestinationColumnName = \"weekday_name\"], [SourceColumnName = \"weekday_name_short\", DestinationColumnName = \"weekday_name_short\"], [SourceColumnName = \"Is_weekend\", DestinationColumnName = \"is_weekend\"], [SourceColumnName = \"season_number\", DestinationColumnName = \"season_number\"], [SourceColumnName = \"season_name\", DestinationColumnName = \"season_name\"], [SourceColumnName = \"season_name_short\", DestinationColumnName = \"season_name_short\"], [SourceColumnName = \"promotion_seasonality\", DestinationColumnName = \"promotion_seasonality\"]},\r\n    SourceColumns = Table.SelectColumns(Query, List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\n","connectionOverrides":[{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Query","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Query.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"sk_date\"]}]"}],"attributes":[{"name":"sk_date","dataType":"int64"},{"name":"proper_date","dataType":"dateTime"},{"name":"monthday_number","dataType":"int64"},{"name":"weekday_number","dataType":"int64"},{"name":"weekday_name","dataType":"string"},{"name":"quarter_number","dataType":"int64"},{"name":"month_name","dataType":"string"},{"name":"Month","dataType":"int64"},{"name":"Semester number","dataType":"int64"},{"name":"Semester name","dataType":"string"},{"name":"year","dataType":"int64"},{"name":"full_date","dataType":"string"},{"name":"weekday_name_short","dataType":"string"},{"name":"month_name_short","dataType":"string"},{"name":"season_number","dataType":"int64"},{"name":"season_name","dataType":"string"},{"name":"season_name_short","dataType":"string"},{"name":"Is_weekend","dataType":"string"},{"name":"promotion_seasonality","dataType":"string"},{"name":"quarter_name","dataType":"string"}]}]}