{"name":"DF interactions - load stg_fact_customer_interactions","ppdf:dataflowId":"0daec705-5f26-483a-b189-22639aeb7bda","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"351c8a57-6d48-47a4-941c-9da16fccacd2"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2025-01-07T16:54:38.2886407+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"customer_interactions_cases":{"queryId":"ed2adbe2-4bd2-42b7-8501-6e8d8f780902","queryName":"customer_interactions_cases","loadEnabled":true},"DefaultStaging":{"queryId":"70b66191-7cc6-4d6a-b12b-bd1522468a89","queryName":"DefaultStaging"},"MaxDate":{"queryId":"d84ded78-db4b-4d5a-9c1e-69852d20937d","queryName":"MaxDate"},"dim_date":{"queryId":"a343ab80-dfa3-4c72-9b5b-55dd30e201fa","queryName":"dim_date","loadEnabled":true},"customer_interactions_cases_DataDestination":{"queryId":"b0a1f0db-1442-404e-8788-2374599d1dc1","queryName":"customer_interactions_cases_DataDestination"},"customer_interactions_cases_WriteToDataDestination":{"queryId":"3c020405-c507-4145-88f9-579c6f27e0f1","queryName":"customer_interactions_cases_WriteToDataDestination"},"customer_interactions_cases_TransformForWriteToDataDestination":{"queryId":"a45b9dfb-a2e6-4476-b645-0e527fd6ab37","queryName":"customer_interactions_cases_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared customer_interactions_cases = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[lakehouseId = \"8deda1cd-e23e-430f-b755-075b107caebd\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"customer_interactions_cases\", ItemKind = \"Table\"]}[Data],\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Navigation 1\", \"new_interaction_date\", each let\r\n    Digits = Text.PadStart(Text.From([interaction_date]), 8, \"0\"),\r\n    Day = Text.Middle(Digits, 0, 2),\r\n    Month = Text.Middle(Digits, 2, 2),\r\n    Year = Text.Middle(Digits, 4, 4)\r\nin\r\n    Date.FromText(Year & \"-\" & Month & \"-\" & Day)), {{\"new_interaction_date\", type date}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Added custom\", {\"customer_id\", \"agent_id\", \"interaction_date\", \"new_interaction_date\", \"interaction_time\", \"reason_id\", \"channel_id\", \"wait_time\", \"resolution_time\", \"satisfaction_score\"}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Reordered columns\", {\"interaction_time\"}),\r\n  Custom = Table.AddColumn(#\"Removed columns\", \"Addition\", each [wait_time] + [resolution_time], Int64.Type),\r\n  #\"Renamed columns\" = Table.RenameColumns(Custom, {{\"Addition\", \"interaction_duration\"}}),\r\n  #\"Custom 1\" = #\"Renamed columns\",\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Custom 1\", {{\"new_interaction_date\", \"new_interacation_date\"}}),\r\n  #\"Custom 2\" = #\"Renamed columns 1\",\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Custom 2\", {{\"interaction_duration\", type number}}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"wait_time\", type number}, {\"resolution_time\", type number}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Changed column type 1\", {\"customer_id\", \"agent_id\", \"reason_id\", \"channel_id\"}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Removed duplicates\", \"new_interacation_date\", \"new_interacation_date - Copy\"),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"new_interacation_date - Copy\", type number}}),\r\n  #\"Renamed columns 2\" = Table.RenameColumns(#\"Changed column type 2\", {{\"new_interacation_date - Copy\", \"lastdate_comparison\"}}),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Renamed columns 2\", {{\"new_interacation_date\", type date}}),\r\n  #\"Changed column type 4\" = Table.TransformColumnTypes(#\"Changed column type 3\", {{\"new_interacation_date\", type datetime}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Changed column type 4\", each [lastdate_comparison] > MaxDate)\r\n\r\n\r\n\r\nin\r\n  #\"Filtered rows\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared MaxDate = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"fact_customer_interactions_cases\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"fk_date\"}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Choose columns\", {\"fk_date\"}, dim_date, {\"sk_date\"}, \"dim_date\", JoinKind.LeftOuter),\r\n  #\"Expanded dim_date\" = Table.ExpandTableColumn(#\"Merged queries\", \"dim_date\", {\"proper_date\"}, {\"proper_date\"}),\r\n  #\"Choose columns 1\" = Table.SelectColumns(#\"Expanded dim_date\", {\"proper_date\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns 1\", {{\"proper_date\", type number}}),\r\n  #\"Drill down\" = #\"Changed column type\"[proper_date],\r\n  Custom = if List.NonNullCount(#\"Drill down\") = 0 then 0 else List.Max(#\"Drill down\")\r\nin\r\n  Custom;\r\nshared dim_date = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"dim_date\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"sk_date\", \"proper_date\"})\r\nin\r\n  #\"Choose columns\";\r\nshared customer_interactions_cases_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"stg_fact_customer_interactions_cases\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"DefaultStaging\"]\r\nshared customer_interactions_cases_WriteToDataDestination = let\r\n  customer_interactions_cases_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = customer_interactions_cases_DataDestination], (txn) => {TableAction.InsertRows(txn[Target], customer_interactions_cases_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  customer_interactions_cases_WriteToDataDestination;\r\nshared customer_interactions_cases_TransformForWriteToDataDestination = let\r\n    ColumnMappings = {[SourceColumnName = \"new_interacation_date\", DestinationColumnName = \"fk_date\"], [SourceColumnName = \"agent_id\", DestinationColumnName = \"fk_agent\"], [SourceColumnName = \"channel_id\", DestinationColumnName = \"fk_channel\"], [SourceColumnName = \"customer_id\", DestinationColumnName = \"fk_customer\"], [SourceColumnName = \"reason_id\", DestinationColumnName = \"fk_reason\"], [SourceColumnName = \"wait_time\", DestinationColumnName = \"wait_time\"], [SourceColumnName = \"resolution_time\", DestinationColumnName = \"resolution_time\"], [SourceColumnName = \"satisfaction_score\", DestinationColumnName = \"satisfaction_score\"], [SourceColumnName = \"interaction_duration\", DestinationColumnName = \"interaction_duration\"]},\r\n    SourceColumns = Table.SelectColumns(customer_interactions_cases, List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null},{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"customer_interactions_cases","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"customer_interactions_cases.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"customer_id\",\"agent_id\",\"reason_id\",\"channel_id\"]}]"}],"attributes":[{"name":"customer_id","dataType":"string"},{"name":"agent_id","dataType":"string"},{"name":"interaction_date","dataType":"int64"},{"name":"new_interacation_date","dataType":"dateTime"},{"name":"reason_id","dataType":"string"},{"name":"channel_id","dataType":"string"},{"name":"wait_time","dataType":"double"},{"name":"resolution_time","dataType":"double"},{"name":"satisfaction_score","dataType":"int64"},{"name":"interaction_duration","dataType":"double"},{"name":"lastdate_comparison","dataType":"double"}]},{"$type":"LocalEntity","name":"dim_date","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"dim_date.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"sk_date","dataType":"int64"},{"name":"proper_date","dataType":"dateTime"}]}]}