{"name":"DF reasons - load DW dim_reason","ppdf:dataflowId":"a073ed6e-adb2-4c7e-9a90-700431c4c34f","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"c821fbf7-1434-4ae1-861c-f97b0b282ebd"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2025-01-08T20:54:51.9623438+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"stg_dim_reason":{"queryId":"757df542-c6e5-416a-b181-ffe26b17faa3","queryName":"stg_dim_reason","loadEnabled":true},"DefaultStaging":{"queryId":"4a6d1e1c-a9e7-4a44-99fe-7b7768532e19","queryName":"DefaultStaging"},"FastCopyStaging":{"queryId":"d6fd85f1-8219-4335-b4ee-e13ad8c02ad5","queryName":"FastCopyStaging"},"stg_dim_reason_DataDestination":{"queryId":"b3be4e2d-c280-455c-bd9b-918ae40f4986","queryName":"stg_dim_reason_DataDestination"},"stg_dim_reason_WriteToDataDestination":{"queryId":"cc513e15-e247-4209-a0db-319115ba33db","queryName":"stg_dim_reason_WriteToDataDestination"},"stg_dim_reason_TransformForWriteToDataDestination":{"queryId":"78679187-2943-4135-8291-6374644b0a31","queryName":"stg_dim_reason_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared stg_dim_reason = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"stg_dim_reason\"]}[Data],\r\n  #\"Added index\" = Table.AddIndexColumn(#\"Navigation 1\", \"Index\", 1, 1, Int64.Type),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Added index\", {{\"Index\", \"sk_reason\"}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Renamed columns\", {\"sk_reason\", \"bk_reason\", \"reason_name\"}),\r\n  #\"Added index 1\" = Table.AddIndexColumn(#\"Reordered columns\", \"Index\", 0, 1, Int64.Type),\r\n  #\"Added index 2\" = Table.AddIndexColumn(#\"Added index 1\", \"Index (2)\", 1, 1, Int64.Type),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Added index 2\", {\"Index (2)\", \"Index\"})\r\nin\r\n  #\"Removed columns\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared FastCopyStaging = let\r\n  FastCopyStaging = Pipeline.FastCopyModelStorage(DefaultStaging, [Required = false])\r\nin\r\n  FastCopyStaging;\r\nshared stg_dim_reason_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"dim_reason\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"DefaultStaging\"]\r\nshared stg_dim_reason_WriteToDataDestination = let\r\n  stg_dim_reason_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = stg_dim_reason_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], stg_dim_reason_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  stg_dim_reason_WriteToDataDestination;\r\nshared stg_dim_reason_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(stg_dim_reason, {\"sk_reason\", \"bk_reason\", \"reason_name\", \"category\", \"type\", \"call_priority\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"stg_dim_reason","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"stg_dim_reason.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"sk_reason","dataType":"int64"},{"name":"bk_reason","dataType":"string"},{"name":"category","dataType":"string"},{"name":"type","dataType":"string"},{"name":"call_priority","dataType":"string"},{"name":"reason_name","dataType":"string"}]}]}