{"name":"DF signups - load stg_fact_signups_record","ppdf:dataflowId":"8dccfc77-82a5-4046-882d-eb6c307f4b9e","ppdf:owner":{"tenantId":"e4bd69ff-e6f7-4c2e-b247-41b54ba2490e","userId":"351c8a57-6d48-47a4-941c-9da16fccacd2"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2025-01-08T20:52:23.5726391+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"signups_record csv":{"queryId":"6d1471b0-3896-4520-9a3f-00a0cd6d4392","queryName":"signups_record csv","loadEnabled":true},"plans_info csv":{"queryId":"f4c20b67-9d69-4a83-aec6-a9fe88e19164","queryName":"plans_info csv","loadEnabled":true},"DefaultStaging":{"queryId":"8fd91054-fc04-4463-a4a4-09cd74cf563b","queryName":"DefaultStaging"},"MaxDate":{"queryId":"529ca367-2f6d-44fd-9291-12fc557aa0cc","queryName":"MaxDate"},"dim_date":{"queryId":"8f498941-0e76-4e71-a565-03fbc4ba98b5","queryName":"dim_date","loadEnabled":true},"signups_record csv_DataDestination":{"queryId":"dfc1f634-90ac-427c-b8ae-0bdfd8894a03","queryName":"signups_record csv_DataDestination"},"signups_record csv_WriteToDataDestination":{"queryId":"bd2085f8-b4b4-4faf-b9e5-572627f2c88b","queryName":"signups_record csv_WriteToDataDestination"},"signups_record csv_TransformForWriteToDataDestination":{"queryId":"c5e6e3a8-6134-471f-94d2-586b23039a15","queryName":"signups_record csv_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared #\"signups_record csv\" = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[lakehouseId = \"8deda1cd-e23e-430f-b755-075b107caebd\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"signups_record.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 2\", [Delimiter = \";\", Columns = 5, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"signup_date\", Int64.Type}, {\"customer_id\", type text}, {\"plan_id\", type text}, {\"termination_date\", Int64.Type}, {\"percentage_discount\", type number}}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"termination_date\", Int64.Type}, {\"signup_date\", type date}}),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Changed column type 1\", {{\"termination_date\", type date}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Changed column type 2\", {\"plan_id\"}, #\"plans_info csv\", {\"plan_id\"}, \"plans_info csv\", JoinKind.LeftOuter),\r\n  #\"Expanded plans_info csv\" = Table.ExpandTableColumn(#\"Merged queries\", \"plans_info csv\", {\"monthly_price\"}, {\"monthly_price\"}),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Expanded plans_info csv\", {{\"monthly_price\", type number}}),\r\n  #\"Inserted date subtraction\" = Table.AddColumn(#\"Changed column type 3\", \"Subtraction\", each Duration.Days([termination_date] - [signup_date]), type nullable Int64.Type),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Inserted date subtraction\", {\"Subtraction\"}),\r\n  #\"Inserted date subtraction 1\" = Table.AddColumn(#\"Removed columns\", \"Subtraction\", each Duration.Days([termination_date] - [signup_date]), type nullable Int64.Type),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Inserted date subtraction 1\", {{\"Subtraction\", \"time_difference\"}}),\r\n  #\"Divided column\" = Table.TransformColumns(#\"Renamed columns\", {{\"time_difference\", each _ / 30, type number}}),\r\n  #\"Rounded down\" = Table.TransformColumns(#\"Divided column\", {{\"time_difference\", each Number.RoundDown(_), Int64.Type}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Rounded down\", null, 1, Replacer.ReplaceValue, {\"time_difference\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Replaced value\", {\"customer_id\", \"plan_id\", \"signup_date\", \"termination_date\", \"time_difference\", \"percentage_discount\", \"monthly_price\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Reordered columns\", null, #date(2023, 12, 31), Replacer.ReplaceValue, {\"termination_date\"}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Replaced value 1\", \"final_price\", each ([monthly_price] * [time_difference]) * (1-[percentage_discount])), {{\"final_price\", type number}}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Added custom\", \"signup_date\", \"signup_date - Copy\"),\r\n  #\"Changed column type 4\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"signup_date - Copy\", type number}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Changed column type 4\", {{\"signup_date - Copy\", \"lastdate_comparison\"}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Renamed columns 1\", each [lastdate_comparison] > MaxDate),\r\n  #\"Changed column type 5\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"signup_date\", type datetime}, {\"termination_date\", type datetime}})\r\n\r\nin\r\n  #\"Changed column type 5\";\r\nshared #\"plans_info csv\" = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[lakehouseId = \"8deda1cd-e23e-430f-b755-075b107caebd\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"plans_info.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 2\", [Delimiter = \";\", Columns = 8, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true])\r\nin\r\n  #\"Promoted headers\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared MaxDate = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"fact_signups_record\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"fk_signup_date\"}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Choose columns\", {\"fk_signup_date\"}, dim_date, {\"sk_date\"}, \"dim_date\", JoinKind.LeftOuter),\r\n  #\"Expanded dim_date\" = Table.ExpandTableColumn(#\"Merged queries\", \"dim_date\", {\"proper_date\"}, {\"proper_date\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded dim_date\", {{\"proper_date\", type number}}),\r\n  #\"Drill down\" = #\"Changed column type\"[proper_date],\r\n  #\"Calculated maximum\" = if List.NonNullCount(#\"Drill down\") = 0 then 0 else List.Max(#\"Drill down\")\r\nin\r\n  #\"Calculated maximum\";\r\nshared dim_date = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data]{[warehouseId = \"56f8d80d-aa09-4986-91b9-0b2b580406a3\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"dim_date\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"sk_date\", \"proper_date\"})\r\nin\r\n  #\"Choose columns\";\r\nshared #\"signups_record csv_DataDestination\" = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"ccb62b89-6526-4fdf-a034-bdccf4329881\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"d3ddbc8d-87ff-4c2d-ad0a-738e1109cee7\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"dbo\", Item = \"stg_fact_signups_record\"]}[Data]\r\nin\r\n  TableNavigation;\r\n[Staging = \"DefaultStaging\"]\r\nshared #\"signups_record csv_WriteToDataDestination\" = let\r\n  #\"signups_record csv_WriteToDataDestination\" = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = #\"signups_record csv_DataDestination\"], (txn) => {TableAction.InsertRows(txn[Target], #\"signups_record csv_TransformForWriteToDataDestination\"), Action.DoNothing}))\r\nin\r\n  #\"signups_record csv_WriteToDataDestination\";\r\nshared #\"signups_record csv_TransformForWriteToDataDestination\" = let\r\n    ColumnMappings = {[SourceColumnName = \"signup_date\", DestinationColumnName = \"fk_signup_date\"], [SourceColumnName = \"termination_date\", DestinationColumnName = \"fk_termination_date\"], [SourceColumnName = \"customer_id\", DestinationColumnName = \"fk_customer\"], [SourceColumnName = \"plan_id\", DestinationColumnName = \"fk_plan\"], [SourceColumnName = \"percentage_discount\", DestinationColumnName = \"percentage_discount\"], [SourceColumnName = \"final_price\", DestinationColumnName = \"final_price\"]},\r\n    SourceColumns = Table.SelectColumns(#\"signups_record csv\", List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null},{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"signups_record csv","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"signups_record%20csv.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"customer_id","dataType":"string"},{"name":"plan_id","dataType":"string"},{"name":"signup_date","dataType":"dateTime"},{"name":"termination_date","dataType":"dateTime"},{"name":"time_difference","dataType":"double"},{"name":"percentage_discount","dataType":"double"},{"name":"monthly_price","dataType":"double"},{"name":"final_price","dataType":"double"},{"name":"lastdate_comparison","dataType":"double"}]},{"$type":"LocalEntity","name":"plans_info csv","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"plans_info%20csv.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"offer_category","dataType":"string"},{"name":"offer_type","dataType":"string"},{"name":"product_name","dataType":"string"},{"name":"monthly_price","dataType":"string"},{"name":"data_allowance","dataType":"string"},{"name":"internet_speed","dataType":"string"},{"name":"description","dataType":"string"},{"name":"plan_id","dataType":"string"}]},{"$type":"LocalEntity","name":"dim_date","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"dim_date.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"sk_date","dataType":"int64"},{"name":"proper_date","dataType":"dateTime"}]}]}